
project_id = "ndqaokjyeimjspxlnzjq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[auth]
enabled = true

# Fix: Removing the invalid [auth.email] section
# The correct configuration for email should be under [auth] if needed

[functions.generate-professional-description]
verify_jwt = false
